apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crateDB.fullname" . }}-config
  labels:
    {{- include "crateDB.labels" . | nindent 4 }}
data:
  crate.yml: |-
{{ .Values.configMaps.crateConfig | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "crateDB.fullname" . }}-logsettings
  labels:
    {{- include "crateDB.labels" . | nindent 4 }}
data:
  log4j2.properties: |-
{{ .Values.configMaps.logSettings | indent 4 }}