kind: Service
apiVersion: v1
metadata:
  name: crate-internal-service
  labels:
    {{- include "crateDB.labels" . | nindent 4 }}
spec:
  # Create a cluster-internal load balancer.
  type: ClusterIP
  ports:
    # Port 4200 for HTTP clients.
  - port: 4200
    name: crate-web
    # Port 5432 for PostgreSQL wire protocol clients.
  - port: 5432
    name: postgres
  selector:
    app: crate
    {{- include "crateDB.selectorLabels" . | nindent 6 }}